use_frameworks!

platform :ios, '8.0'

target 'MJLib_Example' do
  pod 'MJLib', :path => '../'

  target 'MJLib_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
